# Site settings
author: Connie H
title: Code Devine
header-img: img/home-bg.png
email: constance.hyman@mchsi.com
copyright_name: Connie H
description: > # this means to ignore newlines until "baseurl:"
  Musings on the process of learning full-stack web development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Connieh1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
